In [1]:
from shapely.geometry import Point
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster
from folium.plugins import FastMarkerCluster

Reading in files

In [2]:
pbp_2013 = pd.read_csv('../data/pbp_2013.csv', low_memory=False)
pbp_2013.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,2013122913,12/29/2013,3,15,0,DEN,LV,1,10,20,...,20.0,OWN,0,NaN,0,NaN,0,NaN,NaN,NaN
1,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,35,...,35.0,OWN,0,NaN,0,NaN,0,NaN,NaN,NaN

In [3]:
pbp_2014 = pd.read_csv('../data/pbp_2014.csv', low_memory=False)
pbp_2014.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2014113007,11/30/2014,4,2,0,LA,LV,4,3,50,...,0,0,NaN,50,OPP,0,NaN,0,NaN,0
1,2014113007,11/30/2014,4,2,55,LA,LV,2,3,50,...,0,0,CENTER,50,OPP,0,NaN,0,NaN,0

In [4]:
pbp_2015 = pd.read_csv('../data/pbp_2015.csv', low_memory=False)
pbp_2015.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2015112907,11/29/2015,3,7,9,TEN,LV,1,10,84,...,0,0,RIGHT END,16,OPP,0,NaN,0,NaN,0
1,2015112907,11/29/2015,3,7,48,TEN,LV,1,10,67,...,0,0,NaN,33,OPP,0,NaN,0,NaN,0

In [5]:
pbp_2016 = pd.read_csv('../data/pbp_2016.csv', low_memory=False)
pbp_2016.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2016122408,12/24/2016,4,2,38,IND,LV,4,9,75,...,0,0,NaN,25,OPP,0,NaN,0,NaN,0
1,2016122408,12/24/2016,4,2,41,IND,LV,3,9,75,...,0,0,NaN,25,OPP,0,NaN,0,NaN,0

In [6]:
pbp_2017 = pd.read_csv('../data/pbp_2017.csv', low_memory=False)
pbp_2017.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2017123113,12/31/2017,4,7,9,LAC,LV,4,1,93,...,0,0,CENTER,7,OPP,0,NaN,0,NaN,0
1,2017123113,12/31/2017,4,7,53,LAC,LV,3,1,93,...,0,0,RIGHT GUARD,7,OPP,0,NaN,0,NaN,0

In [7]:
pbp_2018 = pd.read_csv('../data/pbp_2018.csv', low_memory=False)
pbp_2018.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2018123004,12/30/2018,4,1,16,KC,LV,4,6,71,...,0,0,NaN,29,OPP,0,NaN,0,NaN,0
1,2018123004,12/30/2018,4,2,0,KC,LV,3,6,71,...,0,0,LEFT END,29,OPP,0,NaN,0,NaN,0

In [8]:
pbp_2019 = pd.read_csv('../data/pbp_2019.csv', low_memory=False)
pbp_2019.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2019112406,11/24/2019,3,6,39,NYJ,LV,0,0,85,...,0,0,NaN,15,OPP,0,NaN,0,NaN,0
1,2019112406,11/24/2019,3,6,44,NYJ,LV,3,1,99,...,0,0,NaN,1,OPP,0,NaN,0,NaN,0

In [9]:
pbp_2020 = pd.read_csv('../data/pbp_2020.csv', low_memory=False)
pbp_2020.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2020112211,11/22/2020,2,5,38,MIA,DEN,2,7,68,...,0,0,LEFT GUARD,32,OPP,0,NaN,0,NaN,0
1,2020112211,11/22/2020,2,4,56,MIA,DEN,3,5,70,...,0,0,NaN,30,OPP,0,NaN,0,NaN,0

Concatenating all 8 dataframes

In [10]:
pbp_all_years = pd.concat([pbp_2013, pbp_2014, pbp_2015, pbp_2016, pbp_2017, pbp_2018, pbp_2019, pbp_2020])
pbp_all_years.head()

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,2013122913,12/29/2013,3,15,0,DEN,LV,1,10,20,...,20.0,OWN,0,NaN,0,NaN,0,NaN,NaN,NaN
1,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,35,...,35.0,OWN,0,NaN,0,NaN,0,NaN,NaN,NaN
2,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,98,...,2.0,OPP,0,NaN,0,NaN,0,NaN,NaN,NaN
3,2013122913,12/29/2013,2,0,18,DEN,LV,1,5,95,...,5.0,OPP,0,NaN,0,NaN,0,NaN,NaN,NaN
4,2013122913,12/29/2013,2,0,22,DEN,LV,2,4,89,...,11.0,OPP,0,NaN,0,NaN,0,NaN,NaN,NaN

In [11]:
pbp_all_years.columns

Index(['GameId', 'GameDate', 'Quarter', 'Minute', 'Second', 'OffenseTeam',
       'DefenseTeam', 'Down', 'ToGo', 'YardLine', 'Unnamed: 10',
       'SeriesFirstDown', 'Unnamed: 12', 'NextScore', 'Description', 'TeamWin',
       'Unnamed: 16', 'Unnamed: 17', 'SeasonYear', 'Yards', 'Formation',
       'PlayType', 'IsRush', 'IsPass', 'IsIncomplete', 'IsTouchdown',
       'PassType', 'IsSack', 'IsChallenge', 'IsChallengeReversed',
       'Challenger', 'IsMeasurement', 'IsInterception', 'IsFumble',
       'IsPenalty', 'IsTwoPointConversion', 'IsTwoPointConversionSuccessful',
       'RushDirection', 'YardLineFixed', 'YardLineDirection',
       'IsPenaltyAccepted', 'PenaltyTeam', 'IsNoPlay', 'PenaltyType',
       'PenaltyYards', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47'],
      dtype='object')

In [12]:
pbp_all_years.shape

(353149, 48)

In [13]:
pbp_all_years = pbp_all_years.loc[:, ~pbp_all_years.columns.str.contains('^Unnamed')]

In [14]:
pbp_all_years.columns

Index(['GameId', 'GameDate', 'Quarter', 'Minute', 'Second', 'OffenseTeam',
       'DefenseTeam', 'Down', 'ToGo', 'YardLine', 'SeriesFirstDown',
       'NextScore', 'Description', 'TeamWin', 'SeasonYear', 'Yards',
       'Formation', 'PlayType', 'IsRush', 'IsPass', 'IsIncomplete',
       'IsTouchdown', 'PassType', 'IsSack', 'IsChallenge',
       'IsChallengeReversed', 'Challenger', 'IsMeasurement', 'IsInterception',
       'IsFumble', 'IsPenalty', 'IsTwoPointConversion',
       'IsTwoPointConversionSuccessful', 'RushDirection', 'YardLineFixed',
       'YardLineDirection', 'IsPenaltyAccepted', 'PenaltyTeam', 'IsNoPlay',
       'PenaltyType', 'PenaltyYards'],
      dtype='object')

In [15]:
pbp_all_years.head(2)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversion,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards
0,2013122913,12/29/2013,3,15,0,DEN,LV,1,10,20,...,0.0,0,RIGHT END,20.0,OWN,0,NaN,0,NaN,0
1,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,35,...,0.0,0,NaN,35.0,OWN,0,NaN,0,NaN,0

In [16]:
pbp_all_years['SeasonYear'] = pbp_all_years['SeasonYear'].fillna(0).astype(np.int64)

In [17]:
pbp_all_years['Yards'] = pbp_all_years['Yards'].fillna(0).astype(np.int64)

In [18]:
pbp_all_years.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 353149 entries, 0 to 34740
Data columns (total 41 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   GameId                          353149 non-null  int64
 1   GameDate                        353149 non-null  object
 2   Quarter                         353149 non-null  int64
 3   Minute                          353149 non-null  int64
 4   Second                          353149 non-null  int64
 5   OffenseTeam                     327030 non-null  object
 6   DefenseTeam                     350176 non-null  object
 7   Down                            353149 non-null  int64
 8   ToGo                            353149 non-null  int64
 9   YardLine                        353149 non-null  int64
 10  SeriesFirstDown                 353149 non-null  int64
 11  NextScore                       353149 non-null  int64
 12  Description                     353145 non-null  object
 13  TeamWin                         353149 non-null  object
 14  SeasonYear                      353149 non-null  int64
 15  Yards                           353149 non-null  int64
 16  Formation                       347203 non-null  object
 17  PlayType                        340885 non-null  object
 18  IsRush                          353149 non-null  object
 19  IsPass                          353149 non-null  object
 20  IsIncomplete                    353148 non-null  object
 21  IsTouchdown                     353149 non-null  int64
 22  PassType                        145889 non-null  object
 23  IsSack                          353149 non-null  object
 24  IsChallenge                     353149 non-null  int64
 25  IsChallengeReversed             353149 non-null  object
 26  Challenger                      8 non-null       float64
 27  IsMeasurement                   353146 non-null  float64
 28  IsInterception                  353149 non-null  int64
 29  IsFumble                        353144 non-null  object
 30  IsPenalty                       353149 non-null  int64
 31  IsTwoPointConversion            353148 non-null  float64
 32  IsTwoPointConversionSuccessful  353149 non-null  int64
 33  RushDirection                   96716 non-null   object
 34  YardLineFixed                   353147 non-null  float64
 35  YardLineDirection               353148 non-null  object
 36  IsPenaltyAccepted               353143 non-null  object
 37  PenaltyTeam                     29385 non-null   object
 38  IsNoPlay                        353146 non-null  object
 39  PenaltyType                     29394 non-null   object
 40  PenaltyYards                    353146 non-null  object
dtypes: float64(4), int64(16), object(21)
memory usage: 113.2+ MB

In [19]:
def Distance(c):
  if c['ToGo'] <= 3:
    return 'Short'
  elif c['ToGo'] <= 6:
    return 'Medium'
  elif 0.0 < c['ToGo'] < 11:
    return 'Long'
  else:
    return 'Distant'

In [20]:
pbp_all_years['Distance'] = pbp_all_years.apply(Distance, axis=1)

In [21]:
pbp_all_years.head(20)

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,Distance
0,2013122913,12/29/2013,3,15,0,DEN,LV,1,10,20,...,0,RIGHT END,20.0,OWN,0,NaN,0,NaN,0,Long
1,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,35,...,0,NaN,35.0,OWN,0,NaN,0,NaN,0,Short
2,2013122913,12/29/2013,2,0,13,DEN,LV,0,0,98,...,0,NaN,2.0,OPP,0,NaN,0,NaN,0,Short
3,2013122913,12/29/2013,2,0,18,DEN,LV,1,5,95,...,0,NaN,5.0,OPP,0,NaN,0,NaN,0,Medium
4,2013122913,12/29/2013,2,0,22,DEN,LV,2,4,89,...,0,NaN,11.0,OPP,0,NaN,0,NaN,0,Medium
5,2013122913,12/29/2013,2,0,40,DEN,LV,1,10,83,...,0,NaN,17.0,OPP,0,NaN,0,NaN,0,Long
6,2013122913,12/29/2013,2,0,57,DEN,LV,2,3,74,...,0,CENTER,26.0,OPP,0,NaN,0,NaN,0,Short
7,2013122913,12/29/2013,2,1,18,DEN,LV,1,10,67,...,0,NaN,33.0,OPP,0,NaN,0,NaN,0,Long
8,2013122913,12/29/2013,2,1,37,DEN,LV,1,10,57,...,0,NaN,43.0,OPP,0,NaN,0,NaN,0,Long
9,2013122913,12/29/2013,2,2,0,DEN,LV,1,10,46,...,0,NaN,46.0,OWN,0,NaN,0,NaN,0,Long
10,2013122913,12/29/2013,2,2,29,DEN,LV,1,10,36,...,0,LEFT TACKLE,36.0,OWN,0,NaN,0,NaN,0,Long
11,2013122913,12/29/2013,2,2,59,DEN,LV,2,1,20,...,0,NaN,20.0,OWN,0,NaN,0,NaN,0,Short
12,2013122913,12/29/2013,2,3,26,DEN,LV,1,10,11,...,0,NaN,11.0,OWN,0,NaN,0,NaN,0,Long
13,2013122913,12/29/2013,2,5,37,DEN,LV,0,0,35,...,0,NaN,35.0,OWN,0,NaN,0,NaN,0,Short
14,2013122913,12/29/2013,2,5,37,DEN,LV,0,0,98,...,0,NaN,2.0,OPP,0,NaN,0,NaN,0,Short
15,2013122913,12/29/2013,2,5,46,DEN,LV,3,4,37,...,0,NaN,37.0,OWN,0,NaN,0,NaN,0,Medium
16,2013122913,12/29/2013,2,6,23,DEN,LV,2,9,32,...,0,NaN,32.0,OWN,0,NaN,0,NaN,0,Long
17,2013122913,12/29/2013,2,6,56,DEN,LV,1,10,31,...,0,CENTER,31.0,OWN,0,NaN,0,NaN,0,Long
18,2013122913,12/29/2013,2,7,28,DEN,LV,3,6,24,...,0,NaN,24.0,OWN,0,NaN,0,NaN,0,Medium
19,2013122913,12/29/2013,2,7,53,DEN,LV,2,12,18,...,0,NaN,18.0,OWN,0,NaN,0,NaN,0,Distant

In [22]:
third_down = pbp_all_years.loc[(pbp_all_years.Down == 3)]                                                             
third_down.head()

,GameId,GameDate,Quarter,Minute,Second,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,...,IsTwoPointConversionSuccessful,RushDirection,YardLineFixed,YardLineDirection,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,Distance
15,2013122913,12/29/2013,2,5,46,DEN,LV,3,4,37,...,0,NaN,37.0,OWN,0,NaN,0,NaN,0,Medium
18,2013122913,12/29/2013,2,7,28,DEN,LV,3,6,24,...,0,NaN,24.0,OWN,0,NaN,0,NaN,0,Medium
22,2013122913,12/29/2013,2,12,47,DEN,LV,3,10,84,...,0,NaN,16.0,OPP,0,NaN,0,NaN,0,Long
25,2013122913,12/29/2013,2,14,40,DEN,LV,3,1,79,...,0,CENTER,21.0,OPP,0,NaN,0,NaN,0,Short
38,2013122913,12/29/2013,1,6,18,DEN,LV,3,6,83,...,0,NaN,17.0,OPP,0,NaN,0,NaN,0,Medium

In [23]:
third_down = third_down.drop(columns = ['Minute', 'Second', 'IsSack', 'IsChallenge', 'IsChallengeReversed',
                                       'Challenger', 'IsMeasurement', 'IsTwoPointConversion',
                                       'IsTwoPointConversionSuccessful', 'YardLineDirection', 'IsPenalty'])
third_down.head()

,GameId,GameDate,Quarter,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,SeriesFirstDown,NextScore,...,IsInterception,IsFumble,RushDirection,YardLineFixed,IsPenaltyAccepted,PenaltyTeam,IsNoPlay,PenaltyType,PenaltyYards,Distance
15,2013122913,12/29/2013,2,DEN,LV,3,4,37,1,0,...,0,0,NaN,37.0,0,NaN,0,NaN,0,Medium
18,2013122913,12/29/2013,2,DEN,LV,3,6,24,1,0,...,0,0,NaN,24.0,0,NaN,0,NaN,0,Medium
22,2013122913,12/29/2013,2,DEN,LV,3,10,84,0,0,...,0,0,NaN,16.0,0,NaN,0,NaN,0,Long
25,2013122913,12/29/2013,2,DEN,LV,3,1,79,1,0,...,0,0,CENTER,21.0,0,NaN,0,NaN,0,Short
38,2013122913,12/29/2013,1,DEN,LV,3,6,83,1,0,...,0,0,NaN,17.0,0,NaN,0,NaN,0,Medium

In [24]:
third_down = third_down.drop(columns = ['PenaltyTeam', 'IsNoPlay', 'PenaltyType', 'PenaltyYards',
                                       'IsPenaltyAccepted'])
third_down.head()

,GameId,GameDate,Quarter,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,SeriesFirstDown,NextScore,...,IsRush,IsPass,IsIncomplete,IsTouchdown,PassType,IsInterception,IsFumble,RushDirection,YardLineFixed,Distance
15,2013122913,12/29/2013,2,DEN,LV,3,4,37,1,0,...,0,1,0,1,DEEP MIDDLE,0,0,NaN,37.0,Medium
18,2013122913,12/29/2013,2,DEN,LV,3,6,24,1,0,...,0,1,0,0,SHORT LEFT,0,0,NaN,24.0,Medium
22,2013122913,12/29/2013,2,DEN,LV,3,10,84,0,0,...,0,1,1,0,SHORT LEFT,0,0,NaN,16.0,Long
25,2013122913,12/29/2013,2,DEN,LV,3,1,79,1,0,...,1,0,0,0,NaN,0,0,CENTER,21.0,Short
38,2013122913,12/29/2013,1,DEN,LV,3,6,83,1,0,...,0,1,0,0,SHORT RIGHT,0,0,NaN,17.0,Medium

In [25]:
third_down.tail()

,GameId,GameDate,Quarter,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,SeriesFirstDown,NextScore,...,IsRush,IsPass,IsIncomplete,IsTouchdown,PassType,IsInterception,IsFumble,RushDirection,YardLineFixed,Distance
34717,2020091301,9/13/2020,3,CLE,BAL,3,9,67,0,0,...,0,1,1,0,SHORT RIGHT,0,0,NaN,33.0,Long
34720,2020091301,9/13/2020,2,BAL,CLE,3,1,93,0,0,...,1,0,0,0,NaN,0,1,CENTER,7.0,Short
34721,2020091303,9/13/2020,4,CAR,LV,3,14,71,1,0,...,0,1,0,0,SHORT LEFT,0,0,NaN,29.0,Distant
34726,2020091000,9/10/2020,2,KC,HOU,3,2,98,1,0,...,0,1,0,1,SHORT RIGHT,0,0,NaN,2.0,Short
34731,2020091300,9/13/2020,4,SEA,ATL,3,3,80,1,0,...,0,1,0,0,SHORT RIGHT,0,0,NaN,20.0,Short

In [26]:
third_down.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56878 entries, 15 to 34731
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GameId           56878 non-null  int64
 1   GameDate         56878 non-null  object
 2   Quarter          56878 non-null  int64
 3   OffenseTeam      56878 non-null  object
 4   DefenseTeam      56878 non-null  object
 5   Down             56878 non-null  int64
 6   ToGo             56878 non-null  int64
 7   YardLine         56878 non-null  int64
 8   SeriesFirstDown  56878 non-null  int64
 9   NextScore        56878 non-null  int64
 10  Description      56878 non-null  object
 11  TeamWin          56878 non-null  object
 12  SeasonYear       56878 non-null  int64
 13  Yards            56878 non-null  int64
 14  Formation        56877 non-null  object
 15  PlayType         56830 non-null  object
 16  IsRush           56878 non-null  object
 17  IsPass           56878 non-null  object
 18  IsIncomplete     56878 non-null  object
 19  IsTouchdown      56878 non-null  int64
 20  PassType         39403 non-null  object
 21  IsInterception   56878 non-null  int64
 22  IsFumble         56878 non-null  object
 23  RushDirection    8474 non-null   object
 24  YardLineFixed    56878 non-null  float64
 25  Distance         56878 non-null  object
dtypes: float64(1), int64(11), object(14)
memory usage: 11.7+ MB

In [27]:
third_down.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56878 entries, 15 to 34731
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GameId           56878 non-null  int64
 1   GameDate         56878 non-null  object
 2   Quarter          56878 non-null  int64
 3   OffenseTeam      56878 non-null  object
 4   DefenseTeam      56878 non-null  object
 5   Down             56878 non-null  int64
 6   ToGo             56878 non-null  int64
 7   YardLine         56878 non-null  int64
 8   SeriesFirstDown  56878 non-null  int64
 9   NextScore        56878 non-null  int64
 10  Description      56878 non-null  object
 11  TeamWin          56878 non-null  object
 12  SeasonYear       56878 non-null  int64
 13  Yards            56878 non-null  int64
 14  Formation        56877 non-null  object
 15  PlayType         56830 non-null  object
 16  IsRush           56878 non-null  object
 17  IsPass           56878 non-null  object
 18  IsIncomplete     56878 non-null  object
 19  IsTouchdown      56878 non-null  int64
 20  PassType         39403 non-null  object
 21  IsInterception   56878 non-null  int64
 22  IsFumble         56878 non-null  object
 23  RushDirection    8474 non-null   object
 24  YardLineFixed    56878 non-null  float64
 25  Distance         56878 non-null  object
dtypes: float64(1), int64(11), object(14)
memory usage: 11.7+ MB

In [28]:
pbp_all_years_success = pbp_all_years

In [29]:
def ThirdDownConversion(c):
  if c['Yards'] >= c['ToGo']:
    return 'Success'
  else:
    return 'Fail'

In [30]:
third_down['ThirdDownConversion'] = third_down.apply(ThirdDownConversion, axis=1)

In [31]:
third_down.head()

,GameId,GameDate,Quarter,OffenseTeam,DefenseTeam,Down,ToGo,YardLine,SeriesFirstDown,NextScore,...,IsPass,IsIncomplete,IsTouchdown,PassType,IsInterception,IsFumble,RushDirection,YardLineFixed,Distance,ThirdDownConversion
15,2013122913,12/29/2013,2,DEN,LV,3,4,37,1,0,...,1,0,1,DEEP MIDDLE,0,0,NaN,37.0,Medium,Success
18,2013122913,12/29/2013,2,DEN,LV,3,6,24,1,0,...,1,0,0,SHORT LEFT,0,0,NaN,24.0,Medium,Success
22,2013122913,12/29/2013,2,DEN,LV,3,10,84,0,0,...,1,1,0,SHORT LEFT,0,0,NaN,16.0,Long,Fail
25,2013122913,12/29/2013,2,DEN,LV,3,1,79,1,0,...,0,0,0,NaN,0,0,CENTER,21.0,Short,Success
38,2013122913,12/29/2013,1,DEN,LV,3,6,83,1,0,...,1,0,0,SHORT RIGHT,0,0,NaN,17.0,Medium,Success

In [32]:
third_down.to_csv(r'C:\Users\14075\Documents\nss\projects\NSS-Capstone-Project\third_down.csv', index = False)

In [33]:
pbp_all_years.to_csv(r'C:\Users\14075\Documents\nss\projects\NSS-Capstone-Project\pbp_all_years.csv', index = False)